### ISSUE TITLE
Got "64bit addressess not supported" when "make qemu CPUS=2"

### ISSUE THREAD

**Issue by interwolf** [mit-pdos/biscuit#12]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go1.14.7 linux/amd64

### Does this issue reproduce with the latest release?

Yes, I also tried go1.15, which has the same problem

### What operating system and processor architecture are you using (`go env`)?

Ubuntu 16.04.7 LTS, Linux kernel 4.15.0-112-generic

GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"

### What did you do?

If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
A link on play.golang.org is best.

make qemu CPUS=2

### What did you expect to see?

get into the Biscuit OS and be able to type "ls"

### What did you see instead?

              BiscuitOS
          go version: go1.10.1
  4763 MB of physical memory
CPUID: family: 6, model: 1a
sse3 true, ssse3 true, sse41 true, sse42 true, avx false
invariant TSC not supported
bmi1 false, bmi2 false
1GB pages not supported
No hardware performance monitoring
panic: 64bit addressess not supported

goroutine 1 [running]:
ahci.attach_ahci(0x8086, 0x2922, 0x2000)
	/home/zym/src/biscuit/biscuit/src/ahci/ahci.go:94 +0x73a
pci.pci_attach(0x8086, 0x2922, 0x0, 0x4, 0x0)
	/home/zym/src/biscuit/biscuit/src/pci/pci.go:221 +0xd2
pci.Pcibus_attach.func2(0x0, 0x4)
	/home/zym/src/biscuit/biscuit/src/pci/pci.go:164 +0x9d
pci.Pcibus_attach()
	/home/zym/src/biscuit/biscuit/src/pci/pci.go:179 +0x53
main.attach_devs(0x5a98e0)
	/home/zym/src/biscuit/biscuit/src/kernel/main.go:952 +0x105
main.main()
	/home/zym/src/biscuit/biscuit/src/kernel/main.go:1654 +0x1f7
 exit with code 0000000000000002 .
halting

**Comment by interwolf** [comment]
Problem solved by upgrading to the latest version of Qemu.

$ qemu-system-x86_64 -version
QEMU emulator version 5.1.0
